version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pangea-dash-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jcnqyi3im50o"
s3_prefix = "pangea-dash-demo"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"

