AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for Dash

Resources:
  Dash:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.8
      Timeout: 300
      Events:
        RootEndpoint:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        DashEndpoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Outputs:
  DashAppURL:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
